'use strict'

const Route = use('Route')

Route.post('/api/sessions', 'SessionController.store').validator('Session')
Route.get('/api/woocommerce', 'WooComerceController.index')

Route.group(() => {
  Route.resource('/api/user_type', 'UserTypeController')
  Route.resource('/api/plan', 'PlanController')
  Route.resource('/api/client', 'ClientController')
  Route.get('/api/listclient', 'ListingController.listClient')
  Route.get('/api/state/sale', 'ListingController.chargesState')
  Route.get('/api/count/client', 'ListingController.countactive')
  Route.get('/api/count/fatura', 'ListingController.totPaid')
  Route.resource('/api/address', 'AddressController')
  Route.resource('/api/user', 'UserController')
  Route.resource('/api/remuneration', 'RemunerationController')
  Route.resource('/api/sale', 'SaleController')
  Route.resource('/api/state', 'StateController')
  Route.resource('/api/city', 'CityController')
  Route.resource('/api/bill', 'BillController')
  Route.resource('/api/charges', 'ChargeController')
  Route.resource('/api/paymentprofile', 'PaymentProfileController')
  Route.resource('/api/paymentmethod', 'PaymentMethodController')
  Route.resource('/api/period', 'PeriodController')
  Route.resource('/api/product', 'ProductController')
  Route.resource('/api/subscription', 'SubscriptionController')
  Route.resource('/api/transaction', 'TransactionController')
  Route.resource('/api/message', 'MessageController')
  Route.resource('/api/issue', 'IssueController')
  Route.resource('/api/notification', 'NotificationController')
  Route.resource('/api/user_remuneration', 'UserRemunerationController')
}).middleware('auth')
